stages:
  data_ingestion:
    cmd: 
      - python src/pipeline/training_pipeline/s1_data_ingestion_pipeline.py
    deps:
      - src/pipeline/training_pipeline/s1_data_ingestion_pipeline.py
      - configuration/config.yaml
    outs:
      - artifacts/data/original_data/Chicken-fecal-images


  model_builder:
    cmd: python src/pipeline/training_pipeline/s2_model_builder_pipeline.py
    deps:
      - src/pipeline/training_pipeline/s2_model_builder_pipeline.py
      - configuration/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/models/base_model



  model_trainer:
    cmd: python src/pipeline/training_pipeline/s3_model_trainer_pipeline.py
    deps:
      - src/pipeline/training_pipeline/s3_model_trainer_pipeline.py
      - src/components/model_callbacks.py
      - configuration/config.yaml
      - artifacts/data/original_data/Chicken-fecal-images
      - artifacts/models/base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/models/trained_model/model.h5
