data:
  source_url: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  data_download_path: artifacts/data/data.zip
  data_original_path: artifacts/data/original_data
  data_original_root_path: artifacts/data/original_data/./
  data_transformed_path: artifacts/data/transformed_data
  

model:
  base_model_path: artifacts/models/base_model/model.h5
  trained_model_path: artifacts/models/trained_model/model.h5
  evaluation_score_json_path: artifacts/models/evaluation_score/scores.json
  mlflow_uri: https://dagshub.com/fhashmi10/ML_Generic.mlflow


callback: 
  callback_path: artifacts/callbacks
  tensorboard_log_path: artifacts/callbacks/tensorboard_logs
  model_checkpoint_path: artifacts/callbacks/checkpoints/model.h5
