data:
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  data_download_path: artifacts/data/data.zip
  data_original_path: artifacts/data/original_data
  data_transformed_path: artifacts/data/transformed_data
  

model:
  base_model_dir: artifacts/models/base_model
  base_model_path: artifacts/models/base_model/model.h5
  trained_model_dir: artifacts/models/trained_model
  trained_model_path: artifacts/models/trained_model/model.h5


callback: 
  callback_dir: artifacts/callbacks
  tensorboard_log_dir: artifacts/callbacks/tensorboard_logs
  model_checkpoint_path: artifacts/callbacks/checkpoints/model.h5

